version: "3.7"

services:
  todo-vue-app:
    image: todo-vue-app
    build: ./TodoAppVue/todo-app
    ports:
      - 8080:8080
  
  todo-net-app:
    image: todo-net-app
    build: ./TodoAppNet
    ports:
      - 5000:5000
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: secret
       MYSQL_DB: todos
